/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.assertEquals;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.firefox.FirefoxDriver;

class AppTest {
    @Test 
    void appHasAGreeting() {
        var browser = new FirefoxDriver();
        browser.get("https://www.google.com");
        var title = browser.getTitle();
        System.out.println(title);
        assertEquals("Google", title);
        browser.close();


    }
}
