/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.firefox.FirefoxOptions;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test
  void appHasAGreeting() {
    var options = new FirefoxOptions();
    // options.setCapability("webSocketUrl", true);
    System.out.println("hello");
    var browser = new FirefoxDriver(options);
    browser.get("https://www.google.com");
    browser.close();
  }
}
